# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  display: 'build image'
stages:
- stage: Build
  displayName: ${display}
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Pay-As-You-Go(8b56ecf7-b521-4669-998b-d3d0e375127e)'
        appName: 'ddkits-laravel'
        deployToSlotOrASE: true
        resourceGroupName: 'DDKits'
        slotName: 'production'
        containers: 'ddkitsprod'