Version: 0.2
phases:
  pre_build:
    commands:
      - echo pre-build started
  build:
    commands:
      - composer install
      - cp extra/.env ./
      - source ddkits.fix.sh &> /dev/null
      - php artisan cache:clear
